---
# Deploys XOS in Docker containers on the CORD head node

- name: Include vars
  hosts: all
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_items:
        - vars/cord_defaults.yml
        - vars/cord.yml
        - vars/example_keystone.yml

- name: XOS setup
  hosts: head
  roles:
    - xos-install

